# Generated by Django 5.1.6 on 2025-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='animais/')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido')], default='Disponível', max_length=20)),
            ],
        ),
    ]
