# Generated by Django 5.1.6 on 2025-02-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_initial'),
        ('animais', '0003_alter_animal_imagem_alter_animal_vendedor'),
    ]

    operations = [
    ]
