# Generated by Django 5.1.6 on 2025-02-16 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_animal_valor_minimo_alter_animal_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='termino_leilao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
