# Generated by Django 5.1.6 on 2025-02-22 07:03

import animais.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_animal_termino_leilao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='animal',
            name='termino_leilao',
            field=models.DateTimeField(default=animais.models.default_termino_leilao),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animais_vendidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
