# Generated by Django 5.1.6 on 2025-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa do Veículo')),
                ('tipo_preco', models.CharField(choices=[('km', 'Preço por km'), ('kg', 'Preço por kg')], max_length=2, verbose_name='Tipo de Preço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Cobrado')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('pix', models.CharField(max_length=100, verbose_name='Chave Pix')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
