# Generated by Django 5.1.6 on 2025-06-03 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='entregador',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo': 'entregador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='pix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='tipo_preco',
            field=models.CharField(choices=[('por_km', 'Por Km'), ('por_kg', 'Por Kg'), ('fixo', 'Fixo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
