# Generated by Django 5.1.6 on 2025-06-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_alter_animal_peso_alter_animal_termino_leilao_and_more'),
        ('entregador', '0002_remove_entregador_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('confirmada', 'Confirmada')], default='pendente', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregador.entregador')),
            ],
        ),
    ]
