# Generated by Django 5.1.6 on 2025-02-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_lance_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
