# Generated by Django 5.1.6 on 2025-02-22 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_lance_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('administrador', 'Administrador')], default='comprador', max_length=20),
        ),
        migrations.AlterField(
            model_name='lance',
            name='comprador',
            field=models.ForeignKey(limit_choices_to={'tipo': 'comprador'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idade', models.IntegerField()),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido'), ('Removido', 'Removido')], default='Disponível', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendedor', models.ForeignKey(limit_choices_to={'tipo': 'vendedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
