# Generated by Django 5.1.6 on 2025-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_tipo_alter_lance_comprador_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('administrador', 'Administrador')], default='vendedor', max_length=20),
        ),
    ]
